module.exports = {
    zoom: 1,
    basemap: 'dark-gray',
    slider: true,
    mapcenter: [0, 0],
    colorramp: [
        [253, 240, 0, 1],
        [255, 218, 0, 1],
        [248, 137, 0, 1],
        [225, 63, 0, 1],
        [229, 0, 2, 1]
    ],
    countryFeatures: {
    'Azerbaijan': 17,
    'Christmas Island': 50,
    'Lesotho': 126,
    'Cayman Islands': 45,
    'Nicaragua': 161,
    'China': 49,
    'Bahrain': 19,
    'Bulgaria': 37,
    'Mexico': 145,
    'Qatar': 184,
    'Saudi Arabia': 200,
    'Guam': 93,
    'Saint Vincent and the Grenadines': 196,
    'Anguilla': 9,
    'Germany': 86,
    'Papua New Guinea': 175,
    'Brazil': 33,
    'Kuwait': 121,
    'Algeria': 5,
    'Mozambique': 153,
    'Bolivia': 28,
    'Zambia': 255,
    'New Zealand': 160,
    'Namibia': 155,
    'Sierra Leone': 204,
    'Reunion': 186,
    'South Sudan': 214,
    'Netherlands': 158,
    'Jersey': 115,
    'Benin': 25,
    'Isle of Man': 110,
    'Philippines': 179,
    'Cook Islands': 55,
    'Bouvet Island': 32,
    'Italy': 112,
    'Greenland': 90,
    'Rwanda': 189,
    'Bahamas': 18,
    'South Korea': 213,
    'Uzbekistan': 246,
    'United States Minor Outlying Islands': 243,
    'Cyprus': 61,
    'Montenegro': 150,
    'Switzerland': 223,
    'Suriname': 219,
    'Sint Maarten': 206,
    'Yemen': 254,
    'Denmark': 64,
    'Turkey': 235,
    'Gambia': 84,
    'Martinique': 141,
    'Northern Cyprus': 167,
    'Afghanistan': 1,
    'Kiribati': 119,
    'Iran': 107,
    'Maldives': 137,
    'Kosovo': 120,
    'Fiji': 77,
    'United Arab Emirates': 241,
    'Russia': 188,
    'Malawi': 135,
    'Brunei': 36,
    'El Salvador': 70,
    'Djibouti': 65,
    'Guinea': 97,
    'Tanzania': 227,
    'Israel': 111,
    'Costa Rica': 56,
    'Saint Lucia': 194,
    'Oman': 170,
    'Palau': 172,
    'Caspian Sea': 44,
    'Chad': 47,
    'Virgin Islands, U.S.': 251,
    'Bangladesh': 20,
    'Belize': 24,
    'Pitcairn Islands': 180,
    'Honduras': 101,
    'Lebanon': 125,
    'Venezuela': 249,
    'Senegal': 201,
    'San Marino': 198,
    'Haiti': 99,
    'Serbia': 202,
    'Nepal': 157,
    'Latvia': 124,
    'Antarctica': 10,
    'Micronesia': 146,
    'Cameroon': 41,
    'French Southern Territories': 82,
    'British Virgin Islands': 35,
    'Egypt': 69,
    'Guyana': 98,
    'Mayotte': 144,
    'Guatemala': 94,
    'Liechtenstein': 129,
    'Malaysia': 136,
    'Saint Pierre and Miquelon': 195,
    'Lithuania': 130,
    'Ireland': 109,
    'Monaco': 148,
    'Tuvalu': 238,
    'United Kingdom': 242,
    'Uganda': 239,
    'Comoros': 54,
    'Saint Helena': 192,
    'Colombia': 53,
    'North Korea': 166,
    'Malta': 139,
    'Clipperton Island': 51,
    'Sao Tome and Principe': 199,
    'Syria': 224,
    'Peru': 178,
    'Northern Mariana Islands': 168,
    'Democratic Republic of the Congo': 63,
    'Spratly islands': 216,
    'Thailand': 228,
    'Spain': 215,
    'Tonga': 232,
    'East Timor': 229,
    'Liberia': 127,
    'Grenada': 91,
    'Hungary': 103,
    'Ukraine': 240,
    'Madagascar': 134,
    'Bosnia and Herzegovina': 30,
    'Dominica': 67,
    'Mali': 138,
    'Akrotiri and Dhekelia': 2,
    'Jordan': 116,
    'Montserrat': 151,
    'Panama': 174,
    'South Georgia and the South Sandwich Islands': 212,
    'Western Sahara': 253,
    'Australia': 15,
    'Cocos Islands': 52,
    'New Caledonia': 159,
    'Iceland': 104,
    'Japan': 114,
    'Kyrgyzstan': 122,
    'Jamaica': 113,
    'Nigeria': 163,
    'Canada': 42,
    'Macedonia': 133,
    'Somalia': 210,
    'Pakistan': 171,
    'Vietnam': 250,
    'Macao': 132,
    'Ethiopia': 74,
    'Belgium': 23,
    'Laos': 123,
    'Georgia': 85,
    'Solomon Islands': 209,
    'Gibraltar': 88,
    'Cambodia': 40,
    'Swaziland': 221,
    'Puerto Rico': 183,
    'French Polynesia': 81,
    'Norfolk Island': 165,
    'Eritrea': 72,
    'Mauritius': 143,
    'Belarus': 22,
    'Tunisia': 234,
    'Guadeloupe': 92,
    'Burundi': 39,
    'Bonaire, Saint Eustatius and Saba': 29,
    'Bermuda': 26,
    'Taiwan': 225,
    'Indonesia': 106,
    'Saint-Barthélemy': 190,
    'Barbados': 21,
    'Republic of Congo': 185,
    'Falkland Islands': 75,
    'France': 79,
    'Bhutan': 27,
    'Slovakia': 207,
    'Paracel Islands': 176,
    'Marshall Islands': 140,
    'Cape Verde': 43,
    'Faroe Islands': 76,
    'Andorra': 7,
    'Nauru': 156,
    'Ghana': 87,
    'Guernsey': 95,
    'South Africa': 211,
    'Sudan': 218,
    'French Guiana': 80,
    'Saint Kitts and Nevis': 193,
    'United States': 244,
    'Svalbard and Jan Mayen': 220,
    'Finland': 78,
    'Hong Kong': 102,
    'Guinea-Bissau': 96,
    'Morocco': 152,
    'Sri Lanka': 217,
    'Botswana': 31,
    'Turks and Caicos Islands': 237,
    'Equatorial Guinea': 71,
    'India': 105,
    'Central African Republic': 46,
    'Aruba': 14,
    'Libya': 128,
    'Czech Republic': 62,
    'Estonia': 73,
    'British Indian Ocean Territory': 34,
    'Kazakhstan': 117,
    'Mongolia': 149,
    'Niue': 164,
    'Seychelles': 203,
    'Sweden': 222,
    'Greece': 89,
    'Luxembourg': 131,
    'Uruguay': 245,
    'Paraguay': 177,
    'Vanuatu': 247,
    'Turkmenistan': 236,
    'Poland': 181,
    'Armenia': 13,
    'Portugal': 182,
    'Kenya': 118,
    'Slovenia': 208,
    'Albania': 4,
    'Croatia': 58,
    'Ecuador': 68,
    'Myanmar': 154,
    'Argentina': 12,
    'Antigua and Barbuda': 11,
    'Saint-Martin': 191,
    'Palestina': 173,
    'Curaçao': 60,
    'Gabon': 83,
    'Vatican City': 248,
    'Burkina Faso': 38,
    'Trinidad and Tobago': 233,
    'Tokelau': 231,
    'Niger': 162,
    'Moldova': 147,
    'Togo': 230,
    'Côte d\'Ivoire': 57,
    'Austria': 16,
    'Zimbabwe': 256,
    'Romania': 187,
    'Tajikistan': 226,
    'Heard Island and McDonald Islands': 100,
    'Dominican Republic': 66,
    'Angola': 8,
    'Norway': 169,
    'Chile': 48,
    'Singapore': 205,
    'Åland': 3,
    'Mauritania': 142,
    'Wallis and Futuna': 252,
    'Samoa': 197,
    'American Samoa': 6,
    'Cuba': 59,
    'Iraq': 10
    },
    colorRampFireHistory: [
        '#FDF000',
        '#F88900',
        '#DE2400',
        '#D40000',
        '#920000'
    ],
    query_results: {},
    regionmap: {},
    maps: {},
    noFeatures: {
        pulpwoodQuery: "There are no fire alerts in pulpwood concessions in the AOI and time range.",
        palmoilQuery: "There are no fire alerts in palm oil concessions in the AOI and time range.",
        loggingQuery: "There are no fire alerts in logging concessions in the AOI and time range.",
        adminQuery: "There are no fire alerts in the AOI and time range.",
        subDistrictQuery: "There are no fire alerts for this AOI and time range.",
        greenpeace: "There are no fire alerts in Greenpeace concessions in the AOI and time range.",
    },
    firesLayer: {
        urlIsland: "https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_ASEAN/MapServer",
        urlGlobal: "https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_Global/MapServer/",
        viirs: 'https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_Global_VIIRS/MapServer/',
        modis: 'https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_Global_MODIS/MapServer',
        global_viirs: 'https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_Global_VIIRS/MapServer/8',
        global_modis: 'https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_Global_MODIS/MapServer/9',
        id: "Active_Fires",
        fire_id: 0,
        fire_id_global_viirs: 8,
        fire_id_global_modis: 9,
        fire_id_island_modis: 0,
        fire_id_island_viirs: 11,
        defaultLayers: [8, 9],
        // defaultLayersModis: [9],
        defaultLayersIsland: [0, 11],
        // defaultLayersIslandModis: [0],
        // defaultLayersIslandViirs: [11],
        //report_fields:{islands:'ISLAND',provinces:'PROVINCE'},
        query: {
            layerId: 0,
            outfields: ["*"],
            fields: [{
                'name': 'LATITUDE',
                'label': 'LATITUDE'
            }, {
                'name': 'LONGITUDE',
                'label': 'LONGITDUE'
            }, {
                'name': 'BRIGHTNESS',
                'label': 'BRIGHTNESS'
            }, {
                'name': 'CONFIDENCE',
                'label': 'CONFIDENCE'
            }, {
                'name': 'ACQ_DATE',
                'label': 'ACQUISITION DATE'
            }, {
                'name': 'ACQ_TIME',
                'label': 'ACQUISITION TIME'
            }]
        }
    },
    adminBoundary: {
        mapDiv: "district-fires-map",
        urlIsland: "https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_ASEAN/MapServer",
        urlGlobal: "https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_Global/MapServer",
        id: 'district-bounds',
        defaultLayers: [6],
        defaultLayersGlobal: [6],
        UniqueValueField: 'DISTRICT',
        UniqueValueFieldGlobal: 'NAME_1',
        regionField: 'PROVINCE',
        regionFieldGlobal: 'NAME_1',
        layerId: 6,
        layerIdGlobal: 6,
        where: "fire_count > 0",
        classBreaksField: 'fire_count',
        classBreaksMethod: 'natural-breaks',
        breakCount: 5,
        fromHex: "#fcddd1",
        toHex: "#930016",
        legendId: "districtLegend",
        queryKey: 'adminQuery',
        loaderId: 'distmapload',
        relatedTableId: "district-fires-table",
    },
    subdistrictBoundary: {
        mapDiv: "subdistrict-fires-map",
        urlIsland: 'https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_ASEAN/MapServer',
        urlGlobal: 'https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_Global/MapServer',
        id: 'subdistrict-bounds',
        defaultLayers: [5],
        defaultLayersGlobal: [4],
        UniqueValueField: 'SUBDISTRIC',
        UniqueValueFieldGlobal: 'NAME_2',
        regionField: 'DISTRICT',
        layerId: 5,
        layerIdGlobal: 4,
        where: "fire_count > 0",
        classBreaksField: 'fire_count',
        classBreaksMethod: 'natural-breaks',
        breakCount: 5,
        fromHex: "#fcddd1",
        toHex: "#930016",
        legendId: "SubDistrict-legend",
        queryKey: 'subDistrictQuery',
        loaderId: 'subdistmapload',
        relatedTableId: "subdistrict-fires-table",
    },
    adminQuery: {
        outFields: ['DISTRICT', 'fire_count'],
        outFieldsGlobal: ['NAME_1', 'fire_count'],
        tableId: "district-fires-table",
        headerField: ['DISTRICT'],
        headerFieldGlobal: ['NAME_1'],
        UniqueValueField: 'DISTRICT',
        UniqueValueFieldGlobal: 'NAME_1',
        layerId: 6,
        layerIdGlobal: 4,
        fire_stats: {
            id: 0,
            id_modis: 0,
            id_viirs: 11,
            outField: 'fire_count',
            onField: 'DISTRICT'
        },
        fire_stats_global: {
            id: 0,
            id_viirs: 8,
            id_modis: 9,
            outField: 'fire_count',
            onField: 'NAME_1'
        }
    },
    subDistrictQuery: {
        outFields: ['SUBDISTRIC', 'DISTRICT', 'fire_count'],
        outFieldsGlobal: ['NAME_2', 'NAME_1', 'fire_count'],
        tableId: "subdistrict-fires-table",
        UniqueValueField: 'SUBDISTRIC',
        UniqueValueFieldGlobal: 'NAME_2',
        regionField: 'DISTRICT',
        regionFieldGlobal: 'NAME_1',
        headerField: ['SUBDISTRICT', 'DISTRICT'],
        headerFieldGlobal: ['NAME_2', 'NAME_1'],
        fire_stats: {
            id: 0,
            id_modis: 0,
            id_viirs: 11,
            outField: 'fire_count',
            onField: 'SUBDISTRIC'
        },
        fire_stats_global: {
            id: 0,
            id_viirs: 8,
            id_modis: 9,
            outField: 'fire_count',
            onField: 'NAME_2'
        },
        layerId: 5,
        layerIdGlobal: 4
    },
    pulpwoodQuery: {
        outFields: ['pulpwoodt', 'fire_count'],
        tableId: "pulpwood-fires-table",
        headerField: ['NAME'],
        fire_stats: {
            id: 0,
            outField: 'fire_count',
            onField: 'pulpwoodt'
        },
        layerId: 5
    },
    palmoilQuery: {
        outFields: ['palm_oilt', 'fire_count'],
        tableId: "palmoil-fires-table",
        headerField: ['NAME'],
        fire_stats: {
            id: 0,
            outField: 'fire_count',
            onField: 'palm_oilt'
        },
        layerId: 5
    },
    loggingQuery: {
        outFields: ['loggingt', 'fire_count'],
        tableId: "logging-fires-table",
        headerField: ['NAME'],
        fire_stats: {
            id: 0,
            outField: 'fire_count',
            onField: 'loggingt'
        },
        layerId: 5
    },
    rspoQuery: {
        outFields: ['palm_oil', 'fire_count'],
        tableId: "rspo-cert-table",
        headerField: ['NAME'],
        groupByFieldsForStatistics: ['CERT_SCHEM', 'palm_oil'],
        fire_stats: {
            id: 0,
            outField: 'fire_count',
            onField: 'palm_oil'
        },
        layerId: 5
    },
    concessionsQuery: {
        outFields: ['concessionname', 'groupname', 'concession', 'totalfires'],
        tableId: 'all-concessions-fires-table',
        headerField: ['CONCESSION NAME', 'GROUP', 'CONCESSION TYPE'],
        UniqueValueField: 'groupname',
        regionField: 'concession',
        layerId: 6,
        chartId: 'concession'
    },

    queryUrl: "https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_ASEAN/MapServer",
    queryUrlGlobal: "https://gis-gfw.wri.org/arcgis/rest/services/Fires/FIRMS_Global/MapServer",
    companyConcessionsId: 1,
    confidenceFireId: 0,
    dailyFiresId: 8,
    dailyFiresField: 'ACQ_DATE',
    reportOptions: {},
    firesCountViirs: null,
    firesCountModis: null
};
